version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=specialty_bookstore
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/specialty_bookstore
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
      
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  mysql_data: